[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --buildFuture --themesDir ../.. -b $DEPLOY_PRIME_URL"

[build.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_THEME = "repo"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "cd exampleSite && hugo --gc --minify --buildFuture --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_THEME = "repo"

[context.branch-deploy]
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_THEME = "repo"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

# Environment variables with HUGO_ prefix for security compliance
# These should be set in Netlify dashboard under Site settings > Environment variables:
# HUGO_RESUME_GOOGLE_DRIVE_LINK = "your_google_drive_link_here"
# HUGO_RESUME_PASSWORD = "your_secure_password_here"
HUGO_ENABLEGITINFO = "true"
